
# 附魔黑名单
# 下列附魔无法被识别分析，也就无法分离/洗去
# 具体附魔类型请前往插件文档查看or官方API查看
noRemoveEnchants:
  - 'ARROW_DAMAGE'
  - 'DIG_SPEED'
# 带此Lore的物品无法分析附魔
noRemoveLore: '&b不可放入附魔分析器'

# 分离附魔消耗等级
splitCostExperience: true
# 分离附魔消耗金币 (需要Vault)
splitCostMoney: false
# 分离附魔消耗点卷 (需要PlayerPoints)
splitCostPoints: false

# 洗去附魔消耗等级
grindCostExperience: true
# 洗去附魔消耗金币 (需要Vault)
grindCostMoney: false
# 洗去附魔消耗点卷 (需要PlayerPoints)
grindCostPoints: false


#############
# 默认权限设置 #
#############

# 此设置限制了一次能够分析出来的附魔的数量,最少为1
visibleEnchantmentsCount: 3

# 分离附魔等级消耗数
splitExperienceCost: 5
# 分离附魔金币消耗数
splitMoneyCost: 500
# 分离附魔点卷消耗数
splitPointsCost: 5

# 洗去附魔等级消耗数
grindExperienceCost: 1
# 洗去附魔金币消耗数
grindMoneyCost: 100
# 分离附魔点卷消耗数
grindPointsCost: 1

# 分离附魔成功率（百分率，100为一定成功）
splitSuccessRate: 100
# 洗去附魔成功率（百分率，100为一定成功）
grindSuccessRate: 100

